# Generated by Django 5.0.3 on 2024-03-19 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.product_master')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.retailer_master')),
            ],
        ),
    ]
