# Generated by Django 5.0.3 on 2024-03-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ret_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('lnb', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('dish', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('kit', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.retailer_master')),
            ],
        ),
    ]
