# Generated by Django 5.0.3 on 2024-03-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0004_ret_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ret_product',
            new_name='to_ret_product',
        ),
        migrations.RenameField(
            model_name='to_ret_product',
            old_name='cable',
            new_name='cable2',
        ),
        migrations.RenameField(
            model_name='to_ret_product',
            old_name='dish',
            new_name='dish2',
        ),
        migrations.RenameField(
            model_name='to_ret_product',
            old_name='kit',
            new_name='kit2',
        ),
        migrations.RenameField(
            model_name='to_ret_product',
            old_name='lnb',
            new_name='lnb2',
        ),
    ]
