# Generated by Django 5.0.3 on 2024-03-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0005_rename_ret_product_to_ret_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable3', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('lnb3', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('dish3', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('kit3', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('sl_date3', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sale_to_ret_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable4', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('lnb4', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('dish4', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('kit4', models.PositiveIntegerField(default=0, max_length=50, null=True)),
                ('sl_date4', models.DateField(null=True)),
                ('retailer4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.retailer_master')),
            ],
        ),
    ]
