# Generated by Django 5.0.3 on 2024-03-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0006_sale_product_sale_to_ret_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='box_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_slno', models.CharField(max_length=50, null=True)),
                ('b_vscno', models.CharField(max_length=50, null=True)),
                ('b_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.box_master')),
            ],
        ),
    ]
