# Generated by Django 5.0.3 on 2024-03-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0007_box_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_product',
            name='b_slno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='box_product',
            name='b_vscno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='box_retailer_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(null=True)),
                ('sl_date', models.DateField(blank=True, null=True)),
                ('b_vcsno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.box_product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d2h_manager.retailer_master')),
            ],
        ),
    ]
