# Generated by Django 5.0.3 on 2024-03-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0009_box_product_r_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_product',
            name='woc_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
