# Generated by Django 5.0.3 on 2024-03-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0010_box_product_woc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='box_product',
            name='set',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cable',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dish',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lnb',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='cable3',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='dish3',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='kit3',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='lnb3',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='cable4',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='dish4',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='kit4',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='lnb4',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
