# Generated by Django 5.0.3 on 2024-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0011_box_product_set_alter_product_cable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_product',
            name='set',
            field=models.CharField(choices=[('BOX_ONLY', 'BOX_ONLY'), ('FULL_SET', 'FULL_SET')], max_length=50, null=True),
        ),
    ]
