# Generated by Django 5.0.3 on 2024-03-30 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0012_alter_box_product_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ret_ret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('retailer1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r1', to='d2h_manager.retailer_master')),
                ('retailer2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r2', to='d2h_manager.retailer_master')),
            ],
        ),
    ]
