# Generated by Django 5.0.1 on 2024-04-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d2h_manager', '0013_ret_ret'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_ret_product',
            name='box2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='cable3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='dish3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='kit3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_product',
            name='lnb3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='cable4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='dish4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='kit4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale_to_ret_product',
            name='lnb4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='to_ret_product',
            name='cable2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='to_ret_product',
            name='dish2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='to_ret_product',
            name='kit2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='to_ret_product',
            name='lnb2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
